import "./globals.css";
import "../style/index.scss";
import AppProvider from "@/lib/contextApi/AppProvider";
import ReduxProvider from "@/redux/provider";
import { DirectionProvider } from "@/hooks/useDirection";
import Setting from "@/common/setting/Setting";
import { Toaster } from "sonner";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  
  return (
    <>
      <html lang="en">
        <head>
          <meta httpEquiv="x-ua-compatible" content="ie=edge" />
          <meta name="description" content="Generated by create next app" />
          <meta name="robots" content="noindex, follow" />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
          />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/icon?family=Material+Icons"
          />
        </head>

        <body suppressHydrationWarning={true} className="body-area">
          <ReduxProvider>
            <AppProvider>
              <DirectionProvider>
                {children}
                <Setting />
              </DirectionProvider>
            </AppProvider>
            <Toaster position="top-center" richColors />
          </ReduxProvider>
        </body>
      </html>
    </>
  );
}
